<?php
include_once AP4L_DIR . 'classes/UserModal.php';

use Ap4l\UserModal;

global $wpdb;

$UserModal = new UserModal();

$accName           = $accEmail          = $accAuth           = $accId             = $sync_order_date   = '';
$sync_orders       = $sync_quantity     = $is_active         = 1;
$action            = 'add';
$sync_order_days   = 60;
$selectionOption   = array(
    1 => 'Yes',
    0 => 'No'
);
$readonly          = '';
$readonly_date     = '';
$readonly_date_msg = '';

$action_req = (!empty($_REQUEST['action'])) ? sanitize_text_field($_REQUEST['action']) : '';
$id_req = (!empty($_REQUEST['id'])) ? sanitize_text_field($_REQUEST['id']) : 0;

if (!empty($id_req) && ($action_req == 'edit')) {
    $action   = 'edit';
    $accId    = $id_req;
    $readonly = 'readonly';
    $date_key = 'ap4l_sync_order_notice_status_' . $accId;

    if (get_option($date_key)) {
        $readonly_date     = 'readonly';
        $readonly_date_msg = 'Cron Status';
    }

    $editAccounts = $UserModal->getAccounts($accId);

    if (! empty($editAccounts) && (count($editAccounts) == 1)) {
        $accName         = $editAccounts[0]->title;
        $accEmail        = $editAccounts[0]->email;
        $accAuth         = $editAccounts[0]->auth_token;
        $sync_orders     = $editAccounts[0]->sync_orders;
        $sync_quantity   = $editAccounts[0]->sync_quantity;
        $sync_quantity   = (!empty($sync_orders) && !empty($sync_quantity)) ? $sync_quantity : 0;
        $is_active       = $editAccounts[0]->is_active;
        $sync_order_days = $editAccounts[0]->sync_order_days;
        $sync_order_date = $editAccounts[0]->sync_order_date;
    } else {
        wp_safe_redirect(AP4L_ACCOUNT_URL);
    }
}
?>
<div class="AddAccoutForm">
    <form id="AddAccoutForm" action="" method="post" class="generalFormDesign">
        <h2><?php echo wp_kses($action_req, AP4L_ALLOWED_HTML); ?> Account</h2>
        <hr>
        <table class="form-table" role="presentation">
            <tbody>
                <tr>
                    <th scope="row">
                        <label for="accoutName">Account Title<span>*</span></label>
                    </th>
                    <td>
                        <input class="regular-text" type="text" id="accoutName" name="accoutName" value="<?php echo esc_attr($accName); ?>" autofocus>
                        <p class="description">You can name your account anything, this is only for your own reference.</p>
                    </td>
                </tr>
                <tr>
                    <th scope="row">
                        <label for="emailID">Seller Email<span>*</span></label>
                    </th>
                    <td>
                        <input <?php echo esc_attr($readonly); ?> class="regular-text" type="email" id="emailID" name="emailID" value="<?php echo esc_attr($accEmail); ?>">
                        <p class="description">The email address you use to login to your <?php echo wp_kses(AP4L_NAME, AP4L_ALLOWED_HTML); ?> seller account.</p>
                    </td>
                </tr>
                <tr>
                    <th scope="row">
                        <label for="authToken">Auth Token<span>*</span></label>
                    </th>
                    <td>
                        <input class="regular-text" type="text" id="authToken" name="authToken" value="<?php echo esc_attr($accAuth); ?>">
                        <p class="description">The auth_token can be generated by logging into your seller account at https://seller.autoparts4less.com/ then click on "Seller Business" -> "Auth Token" -> "Generate New Auth Token".</p>

                    </td>
                </tr>
                <?php if ($action == 'edit' && 1 == 0) { ?>
                    <tr>
                        <th scope="row">Account Status</th>
                        <td>
                            <fieldset>
                                <legend class="screen-reader-text">
                                    <span>Account Status</span>
                                </legend>
                                <label for="accStatus">
                                    <input id="accStatus" name="accStatus" type="checkbox"value="1" <?php checked(1, $is_active); ?>>
                                    (Enabled/Disabled)
                                </label>
                            </fieldset>
                        </td>
                    </tr>
                <?php } ?>
                <tr>
                    <th scope="row">Sync Orders?</th>
                    <td>
                        <select id="syncOrders" name="syncOrders">
                            <?php foreach ($selectionOption as $key => $value) { ?>
                                <option value="<?php echo esc_attr($key); ?>" <?php selected($key, $sync_orders); ?>><?php echo esc_html($value); ?></option>
                            <?php } ?>
                        </select>
                        <p class="description">Do you want to pull in orders placed on <?php echo wp_kses(AP4L_NAME, AP4L_ALLOWED_HTML); ?> and have them show up as orders in your WordPress site? If set to "Yes", you can fully manage orders inside of WordPress, including adding tracking numbers here to have them pushed to <?php echo wp_kses(AP4L_NAME, AP4L_ALLOWED_HTML); ?>.</p>
                    </td>
                </tr>
                <tr>
                    <th scope="row">Sync Quantity?</th>
                    <td>
                        <select id="syncQty" name="syncQty">
                            <?php foreach ($selectionOption as $key => $value) { ?>
                                <option value="<?php echo esc_attr($key); ?>" <?php selected($key, $sync_quantity); ?>><?php echo esc_html($value); ?></option>
                            <?php } ?>
                        </select>
                        <p class="description">If set to ‘Yes’, then when you sell a product on <?php echo wp_kses(AP4L_NAME, AP4L_ALLOWED_HTML); ?>, the quantity for this product will be reduced on WordPress.</p>
                    </td>
                </tr>
                <tr>
                    <th scope="row">
                        <label for="syncOrderFrom">Sync orders from the date</label>
                    </th>
                    <td>
                        <input <?php echo esc_attr($readonly_date); ?> class="regular-text" type="date" id="syncOrderFrom" name="syncOrderFrom" value="<?php echo esc_attr($sync_order_date); ?>">
                        <p class="description">The date you choose here will be the earliest date that we will pull orders for from your AutoParts4Less Seller Account. If you have been selling for years on AP4L and you are just now getting started with your Wordpress connection, you might only want to pull in your recent orders starting from today.</p>
                    </td>
                </tr>
                <tr class="d-none">
                    <th scope="row">
                        <label for="syncOrderDays">Sync order status for last number of days</label>
                    </th>
                    <td>
                        <input class="regular-text"  type="number" id="syncOrderDays" name="syncOrderDays" value="<?php echo esc_attr((!empty($sync_order_days)) ? $sync_order_days : 60); ?>">
                        <p class="description">Default = 60. i.e. last 60 days orders should be watch for order status change.</p>
                    </td>
                </tr>

            </tbody>
        </table>
        <input type="hidden" id="formAction" name="formAction" value="<?php echo esc_attr($action_req); ?>"/>
        <input type="hidden" id="formEditId" name="formEditId" value="<?php echo esc_attr($accId); ?>"/>
        <p class="submit">
            <input type="submit" name="submit" id="submit" class="button button-primary" value="Save Changes">
            <a href="<?php echo esc_url(AP4L_ACCOUNT_URL); ?>" class="button button-primary">cancel</a>
            <img class="loaderImage" src="<?php echo esc_url(AP4L_URL); ?>assets/images/loader.gif"/>
        </p>
    </form>
</div>